// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.FRC3260_2016_gearShifter.subsystems;

import org.usfirst.frc3620.FRC3260_2016_gearShifter.RobotMap;
import org.usfirst.frc3620.FRC3260_2016_gearShifter.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Subsystem1 extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DoubleSolenoid doubleSolenoid1 = RobotMap.subsystem1DoubleSolenoid1;
    private final SpeedController speedController0 = RobotMap.subsystem1SpeedController0;
    private final SpeedController speedController1 = RobotMap.subsystem1SpeedController1;
    private final SpeedController speedController2 = RobotMap.subsystem1SpeedController2;
    private final SpeedController speedController3 = RobotMap.subsystem1SpeedController3;
    private final RobotDrive robotDrive41 = RobotMap.subsystem1RobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
	public void driveControl (Joystick joystick) {
		robotDrive41.arcadeDrive(joystick);
	}


    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveCmd());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

